# Generated by Django 4.1.3 on 2023-04-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='media/main/')),
            ],
        ),
    ]
