# Generated by Django 4.0.1 on 2023-04-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contacting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='media/blog/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
